apiVersion: v1
name: techtrends
description: A Helm chart for the TechTrends cloud-native news sharing application
keywords:
  - techtrends
version: 1.0.0
maintainers:
  - name: Heath Lee
    email: heath.lee.ee@gmail.com
